### ISSUE TITLE
In the "Why 1Cademy" section of the homepage, at this zoom level, the images and the text mess up. Please fix them in all zoom levels.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#1170]
![Image](https://user-images.githubusercontent.com/3834517/212735033-bddd04fa-74e4-46f1-b1c3-c339cf7221ff.png)

**Comment by elVengador** [comment]
we required images with same size, that is required beacause we reduced the padding that help to see complete image but in smaller size
We will update with new Murad designs
