### ISSUE TITLE
We dont have background in google cloud logo in about section, how we can improve it?

### ISSUE THREAD

**Issue by elVengador** [ImanYZ/1Cademy-Public#1325]
this is from Nastia Design:

![Image](https://user-images.githubusercontent.com/27080940/216725874-814de779-dfe3-41a4-bf91-4679153bf600.png)

Implementation is not complete yet
![Image](https://user-images.githubusercontent.com/27080940/216725687-6c5e2b3b-9b8d-4bda-8630-05da1a672437.png)

**Comment by NastiaZabolotnaaaaaa** [comment]
@elVengador hi!

![Image](https://user-images.githubusercontent.com/124579294/216965664-86c278a4-0e6a-4c02-8ca8-b402f9397699.png)

we can place this logo on a gray background)
