### ISSUE TITLE
How we can improve topics section?

### ISSUE THREAD

**Issue by elVengador** [ImanYZ/1Cademy-Public#1327]
We have this topics section with Images, designed by Nastia

![Image](https://user-images.githubusercontent.com/27080940/216732149-542d623f-b497-419d-bade-30b25963c985.png)
![Image](https://user-images.githubusercontent.com/27080940/216732164-35fb23fb-3d19-41d1-b6e5-564cab72b0e2.png)

this is the last proposal by Nastia in Dark mode:
![Image](https://user-images.githubusercontent.com/27080940/216732215-b4374c19-b681-44a2-bb8c-8545fef88da1.png)

**Comment by elVengador** [comment]
about image 3
How would be the hover style in link button?

**Comment by elVengador** [comment]
all topic element should be clickeable

**Comment by NastiaZabolotnaaaaaa** [comment]
@elVengador how about this?
![image](https://user-images.githubusercontent.com/124579294/217092251-6039313e-a844-44c3-9970-8dced60cc513.png)
