### ISSUE TITLE
feature/add-scroll-to-node

### ISSUE THREAD

**Issue by elVengador** [ImanYZ/1Cademy-Public#221]
Cases when is used:
- After hiding a node, we should automatically scroll to its first parent.
- If they refresh the page or open it in another computer, it should automatically navigate to that `sNode`, after loading all the nodes on the map.

**Comment by Artemides** [comment]
# Done
- we added scroll to `sNode` when first render
- we added scroll to node when `chosenNode`
- we added scroll to node when `open` child, parent, references and tag
- we added scroll to node when `remove` child, parent, references and tag
- we added scroll to node when hide `offsprings`
- we added scroll to node when `openLinkedNode`
- we added scroll to node when `hideNodeHandler`
- we added scroll to node when `close Sidebars`
- we added scroll to node when delete/propose node `child/improvement` proposal
# peding 
- fix initNodeStatusChange
- `test` propose new child / improvement

**Comment by Artemides** [comment]
# Done 
- fixed initNodeStatusChange 👌
- tested propose new child / improvement 👌
