### ISSUE TITLE
We only need to show the loader when: 1) Loading the page for the first time, 2) Voting on nodes or proposals, 3) Submitting a proposal.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#280]
Right now, when you expand or collapse a node or open its list of parents/children or tags/references, the loader shows up with a dark overlay and goes away very fast.
These should not show up unless you do one of the three items listed above.

**Comment by ImanYZ** [comment]
I still see the loader and the dark background.

**Comment by elVengador** [comment]
we checked in every posible case and we have loader only in first time
