### ISSUE TITLE
For some reason all tags are gone! One cannot add any tag to filter through! They returned after refreshing the page!

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#389]
![Image](https://user-images.githubusercontent.com/3834517/198861059-df6a1230-a5aa-42ee-8f50-64137bd5ffa1.png)

**Comment by ImanYZ** [comment]
I tested it on another computer as well. This happens when 1Cademy is open in the browser for a while and not used. After that, if you open the list of tags in the search sidebar, you see only the tag representing the member's community.


![Image](https://user-images.githubusercontent.com/3834517/198863069-dcea290e-abd7-4f4e-aeea-731dd197def8.png)

**Comment by ImanYZ** [comment]
I think I know why this happens. Probably in the snapshot listener, instead of updating the previous state, they have set the state only to the tag that is changed coming from the snapshot listener.

**Comment by elVengador** [comment]
![Image](https://user-images.githubusercontent.com/27080940/199130366-a049cba2-6bff-4940-a814-2988cdf16075.png)

we have a hook, that made that works:
1. we have a state
2. initializa with chosen tags
3. that state is update when snapshot gets data
4. maybe is waiting the data arrives, so we could improve adding a loader ading allTagLoader
5. also we can improve his dependencies to rebuild the snapshot (take care of inifinity loop)
