### ISSUE TITLE
Clicking pending and accepted proposals that involve changes in the parent/child links completely messes up (removes) the links.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#392]
To reproduce, open the node edit sidebar of the node "Knowledge Graph" then click any of its accepted proposals. Clicking either of them removes the links connected to this node.

**Comment by elVengador** [comment]
Add video Please

**Comment by yashgandhi303** [comment]
@ImanYZ I think this is working fine, we couldn't reproduce it. let us know if you can reproduce it.

**Comment by ImanYZ** [comment]
https://user-images.githubusercontent.com/3834517/201659313-3e231932-f31e-4879-9d79-5619b69e625a.mov
