### ISSUE TITLE
When I click the button to hide all children, I get the attached error message and nothing happens.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#406]
![Image](https://user-images.githubusercontent.com/3834517/198915676-51487fd2-c934-42fb-82df-cfa44cf29dd1.png)

**Comment by elVengador** [comment]
more information to reproduce the error, please
we tried in many scenarios `hide Offsprings` and was working correctly

**Comment by elVengador** [comment]
that happening again with 144 nodes
use this nodes `khCWqIXa9xQiojnEqHCT` and `AEz7BuH5Zvu3yZQi2XA9` to open many childrens

**Comment by ImanYZ** [comment]
This only happens when many nodes are visible on the map.
