### ISSUE TITLE
Develop a back-end endpoint for an instructor to edit the course syllabus. Please read the comments below.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#457]
- For each chapter/subchapter, it should create a "Relation" node that is locked; i.e., everybody can propose improvements/children on them, but all the proposals will be added to the list of pending proposals on the node and will nevery get accepted regardless of the proposal's or nodes' votes.
- The only way to edit/delete these Relation nodes is through this page, only accessible to the instructor of the course.
- Everybody should be able to cite these chapter/subchapter nodes as tags on their proposals.

![Image](https://user-images.githubusercontent.com/3834517/199375225-e612b60a-eb36-4d95-a6fa-07d1cddb7195.png)

**Comment by r3alst** [comment]
We are following issues with this API that we need solve:
- [ ] Signal node changes to user upon deleting node, updating title, content, children, parent etc
- [ ] Untag deleting chapter or sub-chapter node from tag nodes and send signal to usernodes as well
- [ ] Chapters are not getting tagged under Semester node as children.
