### ISSUE TITLE
Setting up a new course in the settings page.

### ISSUE THREAD

**Issue by r3alst** [ImanYZ/1Cademy-Public#539]

**Comment by r3alst** [comment]
We need to following things:
courseCode = "SI691";
semesterName = "Fall 2020";
programName = "MSI";
departmentName = "Information Science";
universityTitle = "University of Michigan - Ann Arbor";

**Comment by ImanYZ** [comment]
- This button should show up under the navbar next to the semester drop-down.
- After they are done entering the data in the modal (pop over), it should open the course settings tab, so that they continue with specifying the course syllabus and the points for different activities.
