### ISSUE TITLE
For some search queries the search sidebar loads forever without returning and results.

### ISSUE THREAD

**Issue by ImanYZ** [ImanYZ/1Cademy-Public#893]
![Image](https://user-images.githubusercontent.com/3834517/204320661-611bbd54-ecab-4888-aeb7-7d92141c107f.png)

**Comment by elVengador** [comment]
in frontend we have a pending request, and in terminal project we have this message
`API resolved without sending a response for /api/searchNodesInNotebook, this may result in stalled requests.`
